### ISSUE TITLE
End-to-end Test

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/draft-guide-cloud-azure#13]
I have tested the guide on:
- [ ] Windows
- [x] macOS
- [ ] Linux

I didn't have any issues running the guide but have a few minor comments/suggestions about the content of the guide itself:

------------

> In order to deploy your microservices, you need to create an Azure Container Registry in the same location where your services will be deployed, and link the registry to a resource group.

I think it should be made clearer why the user needs to create a container registry. This paragraph simply tells them that they need to, but doesn't provide much explanation or context as to why they need to.

>  View the password for your Azure container registry:

When the user runs the `kubectl create secret` command they are instructed to enter their password directly which I don't think is necessarily good practice. I might be overthinking this, but thought it was worth mentioning since simply looking at the shells history can expose the users password. 

> You will need the external IP addresses associated with the system and inventory services to try out your microservices.

In this guide we use LoadBalancers, but it isn't really mentioned or explained in the guide. I think it could be worthwhile explaining to the users that they will be using LoadBalancers to expose the services.

>`-w` in `kubectl get service`

Is there a reason we use the `-w` command? I feel like it just adds an extra instruction to the guide (ctrl+c). I feel like this works better without the `-w` since we already instruct them to wait until the ip is available. 

> [inventory-EXTERNAL-IP] and [system-EXTERNAL-IP]

Throughout this guide we use these two placeholders. This is inconsistent with the other cloud guides which use a more generic [hostname] placeholder I believe. I am not saying one is better than the other, but I think it is worth discussing and deciding which one to use from here on out so that we can ensure all our cloud guides are consistent with one another.

> Where to next?

I think the kubernetes-health guide should be added to this list

**Comment by NimG98** [comment]
> [inventory-EXTERNAL-IP] and [system-EXTERNAL-IP]
>> Throughout this guide we use these two placeholders. This is inconsistent with the other cloud guides which use a more generic [hostname] placeholder I believe. I am not saying one is better than the other, but I think it is worth discussing and deciding which one to use from here on out so that we can ensure all our cloud guides are consistent with one another.

Will discuss with team to change placeholder of azure guide or change in other cloud guides.

Also need to discuss whether to remove `-w` wait in the `kubectl get service` command to keep consistent with other guides.

**Comment by NimG98** [comment]
Addressed other feedback here: https://github.com/OpenLiberty/draft-guide-cloud-azure/commit/0527c849ef1b5e8c7f4e19d6d9c7f723c1dc744e

**Comment by NimG98** [comment]
Removed -w: https://github.com/OpenLiberty/draft-guide-cloud-azure/commit/d6e37988b784f6bcfa6ce60df0c2e234b7c93454
