### ISSUE TITLE
OL Guide review: Deploying microservices to Azure Kubernetes Service

### ISSUE THREAD

**Issue by Rwalls1** [OpenLiberty/draft-guide-cloud-azure#14]
@NimG98 Here are my edits for the guide, the headings represent sections in the guide, Please let me know if you have any questions: 
What you’ll learn
•	Change “There are different cloud-based solutions for running your workloads in a Kubernetes cluster” to You can run your workloads in a Kubernetes cluster with different cloud-based solutions.
•	Change “A cloud-based infrastructure enables you to focus on developing your microservices without worrying about details related to the servers you deploy them to” to To focus on developing your microservices without worrying about details related to the servers you deploy them to, you can enable a cloud-based infrastructure.
•	Change “AKS simplifies the process of running Kubernetes on Azure” to Using AKS simplifies the process of running Kubernetes on Azure.
•	Change “there is a small cost that is associated with deploying this application.” to a small cost is associated with deploying this application.
•	Change “It also returns the pod’s name in the HTTP header” to It also returns the name of the pod in the HTTP header.
•	Change “This demonstrates how communication can be established” to This process demonstrates how communication can be established.

Getting Started
•	Change “The start directory contains the starting project that you will build upon.” to The start directory contains the starting project that you build.
•	Change “The finish directory contains the finished project that you will build” to The finish directory contains the finished project that you build.

Managing an Azure Container Registry
•	Change “the same location where your services will be deployed” to the same location where your services are deployed.
•	Change “In order to deploy your microservices” to To deploy your microservices.

Creating a resource group
o	Change “For this guide, you will create a new resource group” to you must create a new resource group.
o	Change “these new resources will run in the same region” to these new resources run in the same region.
o	Change the “resources are stored at this given location” to resources are stored at the specified Azure location.
o	Change (global) “You will see an output” to You see an output. 
o	Change “specifies the region name that you will be using” to specifies the region name that you use.

Creating a container registry
•	Change “your private container registry will manage” to your private container registry manages.
•	Change “Docker images that you will build” to Docker images that you build
•	Change “You are using a Basic SKU because it is cheaper and the services you will deploy” to You use a Basic SKU because it is cheaper and the services you deploy.

Logging into the container registry
•	Change “log into” to log in to.
•	Change “,in order to push Docker images to your registry” to to push Docker images to your registry.
•	Change “using the Azure CLI” to by using the Azure CLI.
•	Change “you will see” to you see.
•	Change “the following” to the following message.

Building your Docker images

•	Change “Each microservice resides” to Each microservice exists.
•	Change “you will build your Docker images” to build your Docker images.
•	Change “you need to have Docker installed and your Docker daemon installed” to you need to install Docker and start your Docker daemon.

Pushing the images to a container registry
•	Change “create pods using your container images” to create pods by using your container images.

Provisioning a cluster
•	Change “You may need” to You might need.
•	Change “could also be added” to can also be added.
•	Change “create a cluster with a certain number of nodes” to create a cluster with some nodes.
•	Change “three nodes will be assigned” to three nodes are assigned.
•	Change “which is an identity used” to which is an identity that is used.
•	Change “However, in order to” to However, to
•	Change “this new service prinicipal” to this new service principal.
•	Change “Once the cluster is created” to When the cluster is created.
•	Change “Kubernetes configuration using” to Kubernetes configuration by using.
•	Change “cluster credentials is located at ~/.kube/config.” to cluster credentials is located within the ~/.kube/config filepath.

Storing registry credentials in a secret
•	Change “should replace [email-address]” to replaces [email-address]”

Deploying your application
•	Change “In order to deploy your microservices” to To deploy your microservices.
•	Change “resources defined kubernetes.yaml” to resources defined in the kubernetes.yaml file.

Making requests to the microservices
•	Change “You will need the external IP addresses associated with the system” to You need the external IP addresses that are associated with the system.
•	Change “hostname you will” to hostname that you will.
•	Change “substitute into [hostname].” to substitute into the [hostname] credential.
•	Change “You will need to wait” to You need to wait.
•	Change “Once the [EXTERNAL-IP] appears” to When the [EXTERNAL-IP] appears.

Testing the microservices
•	Change “test the basic functionality” to test the basic functions.
•	Change “if a test failure occurs, then you might have introduced a bug into the code” to If a test failure occurs, then the code might have a bug.

Running the tests
•	Change “If the tests pass, you will see” to If the tests pass, you see.

Tearing down the environment
•	Change “additional” to extra.
•	Change “this command will remove the resource” to this command removes the resource.

**Comment by Rwalls1** [comment]
@NimG98 Let me know when updates have been made, Thanks

**Comment by NimG98** [comment]
- Getting Started:
    - didn't change this section, as it's in all other OL guides, and wanted to keep this guide consistent with that

- Change (global) “You will see an output” to You see an output.
    - I think will sounds better in this case

**Comment by NimG98** [comment]
Other feedback addressed here: https://github.com/OpenLiberty/draft-guide-cloud-azure/commits/dev

**Comment by Rwalls1** [comment]
@NimG98 The updates look good.
