### ISSUE TITLE
Gilbert's feedback for dev content review

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-cloud-azure#2]
- [x] the guide should be under the "More Guides" category instead of "MicroProfile Guides"
- [x] the description wording in the card is not similar to other cloud gudies (i.e. not starting "Explore...")  
- [x] the description in the top of the guide, "....your microservices application ..." > "... microservices..."
- [x] 15 mins should not be long enough
- "What you’ll learn"
    - [x] The paragraph "The two microservices that..." should be same as IBM cloud or AWS guide
- "Managing an Azure Container Registry"
    - [x] the 1st statement "In order to deploy y..." and the 2nd statement "Your Azure Container Registry ..." looks like same. Can combine them and remove the 2nd statement?
    - [x] following statement not clear to me and the word "specfied" typo
        - " If resources are created without specifying a location and created after creating a resource group, these new resources will run in the same region specfied by the resource group location."
    - [x] The statement "The name column specifies..." can be put under the output table and before the statement "However..."
    - [x] Reword the following statement where "create" and "replace" should be in different context
        -  "Create a resource group and replace [location] ..." 
    - [x] should make the output of the `az group create` command scroll-able 
    - [x] should make the output of the `az acr create` command scroll-able 
    - [x] The paragraphs "In the az acr create ..." and "The possible Stock Keeping Unit (SKU) ..." should be moved just after the green command box and before the "You will see an output ..."
    - [x] "... in order to be able to push ..." -> "... in order to push ..."
    - [x] In the passwords output for `  "name": "password",`, better not use "password" as the sample of name
- "Uploading images to a container registry"
    - [x] add following statement as IBM cloud and AWS guides
        - "If you’re unfamiliar with Dockerfiles, check out the Using Docker containers to develop microservices guide."
- "Creating a Kubernetes cluster on AKS"
    - [x] typo: thatyou
- "Deploying microservices to AKS"
    - [x] in the output for the inventory EXTERNAL-IP with the LoadBalancer, the data  is not aligned correctly
    - [x] "To access the application and your microservices,..." -> "To access your microservices,..."
    - [x] The wording of "substituting the appropriate hostnames" should be consistent with the URLs
- Testing the microservices
    - [x] no need to create test classes, do same as IBM cloud and aws guides (unless there is a good reason)

**Comment by NimG98** [comment]
> In the passwords output for "name": "password",, better not use "password" as the sample of name

- The actual JSON output actually has `"name": "password"` there.

**Comment by gkwan-ibm** [comment]
> > In the passwords output for "name": "password",, better not use "password" as the sample of name
> 
>     * The actual JSON output actually has `"name": "password"` there.

OK, then you can check this item as addressed

**Comment by gkwan-ibm** [comment]
-  [ ] the abstract wording in the card at the main board (not the description under the title in the guide )  is not similar to other cloud gudies (i.e. not starting "Explore...")
- Making requests to the microservices
    - [ ] should not be "your local JVM"? may be "the container JVM"  
        - In the second URL, you see a result in JSON format with the system properties of your local JVM.
