### ISSUE TITLE
Peer review feedback

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-cloud-azure#4]
What you'll learn

- [ ] It also returns the pod’s name in the HTTP header, making replicas easy to distinguish from each other. The inventory microservice adds the properties from the system microservice to the inventory. This demonstrates how communication can be established between pods inside a cluster.
=> For the mentioned of "pods" in this section, there's no explanation of what it is. I think for a fresh user, it may be helpful. 

Prerequisites

- [x] For the Docker prereq, it's good to add another sentence for user to start the docker daemon, if they already have docker installed previously. This is needed at one of the step (ie, `az acr login -n guideRegistry`) later, but it wasn't mentioned to have it running. 

- [x] Took a while to install Azure CLI on my MacOS system, as there were a few permission issues, ie, failed to create folder under `/usr/local` directory, failed to make symbolic links within this folder, etc. Had to manually create a folder and change some folder's permissions with the `sudo` command to get through with the installation. 
=> Not sure anything can be done with this, just to note the issues.

- [x] Use the Azure CLI to download and install kubectl with the following command: 
=> Perhaps should say, "If you don't have it already, you can use the Azure CLI to download and install Kubectl.." because one may have `kubectl` installed on their system already. 
=> Then, not sure whether it needs to be up to date

Managing an Azure Container Registry

- [x] In order to deploy your microservices, you need to create an Azure Container Registry in the same location as where your services will be deployed, and link the registry to a resource group.
=> perhaps keep one of "as" or "where" but not both? 

Creating a container registry

- [x] The --admin-enabled flag indicates that the admin user is enabled. 
=> this flag is not used in the command `az acr create -g guideGroup -n guideRegistry --sku Basic --admin-enabled`. 
=> Ah, I realized later that the problem is that this command is long and it's not displayed entirely when the browser screen is not maximized. So this is an UI issue that need to be addressed, imo. 

Logging into the container registry

- [x] The `az acr credential show -n guideRegistry' command shows 2 different passwords.. 

```
{
  "passwords": [
    {
      "name": "password",
      "value": "[password]"
    },
    {
      "name": "password2",
      "value": "[password2]"
    }
  ],
  "username": "guideRegistry"
}

```

Building your Docker images

- [x] Your two images inventory and system should appear in the list of all Docker images: => wonder if it may be good to mention the `system` image first, ie, "Your two images `system` and `inventory` should appear in the list of all Docker images:". It's really minor, and I see why you had it the way you did, cus the `inventory` image shows up first on the first. Just thought to be consistent with the way usually the `system` and `inventory` services are mentioned. 

Pushing the images to a container registry

- [x] Pushing the images to a registry allows the cluster to create pods by using your container images. => I think the word "by" is not needed here? 
=> Optionally may be good to add a short reminder description of what pods are, may be helpful to some users. Or perhaps why to create pods? 

- [x] Just thought for the following commands, you may want to arrange the orders (if they are not mandatory) so that they're consistent with the previous section, and whenever the two services are mentioned, ie, usually the `system` service first then the `inventory` service. 

```
docker tag inventory:latest guideregistry.azurecr.io/inventory
docker tag system:latest guideregistry.azurecr.io/system
```
and 
```
docker push guideregistry.azurecr.io/inventory
docker push guideregistry.azurecr.io/system
```

Provisioning a cluster

- [x] To create your AKS cluster, use the az aks create cluster command. You might need to wait a while your cluster is being created. 
=> "You may" instead of "You might" 
=> perhaps just "wait while", no need the "a"? 

- [x] Some longer commands like this one below is not showing up entirely on the command box, and can't be scrolled to display it as well. This seems like a UI issue, and it's not good, imo. Note, I didn't capture all of the impacted command, as I wasn't sure whether it was cut off or not. 

![image](https://user-images.githubusercontent.com/33134427/60290215-42ac5100-98e6-11e9-84db-4e7138cda504.png)`

- [ ] The `az aks create -g guideGroup --name guideCluster --generate-ssh-keys` command failed for the subscription location I selected, ie, "canadaeast".  Error message below: 
```
Finished service principal creation[##################################]  100.0000%Operation failed with status: 'Bad Request'. Details: The VM size of AgentPoolProfile:nodepool1 is not allowed in your subscription in location 'canadaeast'. The available VM sizes are Standard_M128,Standard_M128-32ms,Standard_M128-64ms,Standard_M128m,Standard_M128ms,Standard_M128s,Standard_M16-4ms,Standard_M16-8ms,Standard_M16ms,Standard_M32-16ms,Standard_M32-8ms,Standard_M32ls,Standard_M32ms,Standard_M32ts,Standard_M64,Standard_M64-16ms,Standard_M64-32ms,Standard_M64ls,Standard_M64m,Standard_M64ms,Standard_M64s,Standard_M8-2ms,Standard_M8-4ms,Standard_M8ms
```

=> At this point, I deleted the azure group, guideGroup, using the tear down command, '`az group delete --name guideGroup --yes --no-wait`. Waited a bit for it to complete. Then try to start the guide again with another location, ie, centralus that was working with others. However, got the following error when trying to login to the container registry: 

```
az acr login -n guideRegistry
Unable to get AAD authorization tokens with message: An error occurred: CONNECTIVITY_CHALLENGE_ERROR
Registry 'guideregistry.azurecr.io' did not issue a challenge.
Error response from daemon: login attempt to https://guideregistry.azurecr.io/v2/ failed with status: 404 Not Found
```
=> Delete the group again, and this time, restarted Docker Desktop with both the docker and kubernetes services refreshed, the above issue doesn't show up again. 

- [x] I think at this point, the kubenetes services, ie, from the Docker Desktop on Mac, should be started, but it wasn't instructed to do so. Perhaps adding a sentence to have it started at the prereqs would be enough and useful.

Making requests to the microservices

- [x] You will need the external IP addresses associated with system and inventory to try out your microservices. => perhaps change to "You will need the external IP addresses associated with the `system` and `inventory` services to try out your microservices."?

- [x] Running one of the following command holds the command prompt, so perhaps they should be separated into 2 command boxes? 

```
kubectl get service/system-service -w
kubectl get service/inventory-service -w
```

- [x] Again, may be good to have the `system` service url mentioned and described before the `inventory`: 

```
http://[inventory-EXTERNAL-IP]:9081/inventory/systems

http://[system-EXTERNAL-IP]:9080/system/properties

The first URL returns an empty list is expected because no system properties are stored in the inventory yet. In the second URL, you see a result in JSON format with the system properties of the container JVM.
```

Suddenly, it seems the azure group is not responding. So couldn't finish testing the services. Went through the entire guide, it's good guide. Will try again.

**Comment by evelinec** [comment]
Tested the guide with the `centralus` location successfully on MacOS.

**Comment by NimG98** [comment]
> Took a while to install Azure CLI on my MacOS system, as there were a few permission issues, ie, failed to create folder under /usr/local directory, failed to make symbolic links within this folder, etc. Had to manually create a folder and change some folder's permissions with the sudo command to get through with the installation.

I tried the command to install Azure CLI (from the link on the guide: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest), which was `brew update && brew install azure-cli`, on a different Mac and it worked fine. So i think it might be a problem with your Mac system specifically.

**Comment by NimG98** [comment]
> "It also returns the pod’s name in the HTTP header, making replicas easy to distinguish from each other. The inventory microservice adds the properties from the system microservice to the inventory. This demonstrates how communication can be established between pods inside a cluster."
=> For the mentioned of "pods" in this section, there's no explanation of what it is. I think for a fresh user, it may be helpful.

The paragraph above is the same as the one in the "What you'll learn" section in the cloud-aws guide and cloud-ibm guide, and in those guides there is no previous explanation of what "pods" are. Should I keep it consistent with those guides? Or should I add a section explaining what pods are, and then make an issue for the other 2 cloud guides to add a pod section in there too?

**Comment by NimG98** [comment]
> - [ ] The --admin-enabled flag indicates that the admin user is enabled. 
=> this flag is not used in the command `az acr create -g guideGroup -n guideRegistry --sku Basic --admin-enabled`. 
=> Ah, I realized later that the problem is that this command is long and it's not displayed entirely when the browser screen is not maximized. So this is an UI issue that need to be addressed, imo. 

> - [ ] Some longer commands like this one below is not showing up entirely on the command box, and can't be scrolled to display it as well. This seems like a UI issue, and it's not good, imo. Note, I didn't capture all of the impacted command, as I wasn't sure whether it was cut off or not. 
![image](https://user-images.githubusercontent.com/33134427/60290215-42ac5100-98e6-11e9-84db-4e7138cda504.png)`


This is a UI issue, that occurs on the openliberty.io site and draft site:
https://github.com/OpenLiberty/openliberty.io/issues/1235

**Comment by NimG98** [comment]
> Logging into the container registry
> - [ ] The `az acr credential show -n guideRegistry' command shows 2 different passwords.. 

- Both of the given passwords work when logging in. But most other guides log in with the first password.

Question:
- Should I leave `az acr credential show -n guideRegistry` which shows a JSON with 2 passwords, and tell users to use either one?
- Or replace that command with `az acr credential show -n guideRegistry --query "passwords[0].value" -o tsv`? This command is used widely by other azure guides. This command automatically only gets the 1st password, and doesn't confuse the user why there's another password.

**Comment by gkwan-ibm** [comment]
> @evelinec
> 
> > "It also returns the pod’s name in the HTTP header, making replicas easy to distinguish from each other. The inventory microservice adds the properties from the system microservice to the inventory. This demonstrates how communication can be established between pods inside a cluster."
> > => For the mentioned of "pods" in this section, there's no explanation of what it is. I think for a fresh user, it may be helpful.
> 
> Question:
> 
>   The paragraph above is the same as the one in the "What you'll learn" section in the cloud-aws guide and cloud-ibm guide, and in those guides there is no previous explanation of what "pods" are. Should I keep it consistent with those guides? Or should I add a section explaining what pods are, and then make an issue for the other 2 cloud guides to add a pod section in there too?

We can keep it consistent with aws and ibm cloud guide. Because there is a link to the "Deploying microservices to Kubernetes" guide where explains what "pod" is. No need to explain in the cloud guides

**Comment by gkwan-ibm** [comment]
>    For the Docker prereq, it's good to add another sentence for user to start the docker daemon, if they already have docker installed previously. This is needed at one of the step (ie, `az acr login -n guideRegistry`) later, but it wasn't mentioned to have it running.

It is not necessary to add the statement "Your Docker daemon must be started in order to perform the steps of this guide." The reasons are:
- keep the consistent as other Cloud guides and guides using Docker
- "daemon" maybe a term for unix platform and not for Windows

**Comment by gkwan-ibm** [comment]
> @evelinec
> 
> > Logging into the container registry
> > 
> > * [ ]  The `az acr credential show -n guideRegistry' command shows 2 different passwords..
> 
>     * Both of the given passwords work when logging in. But most other guides log in with the first password.
> 
> 
> Question:
> 
>   Should I leave `az acr credential show -n guideRegistry` which shows a JSON with 2 passwords, and tell users to use either one?
> 
>   Or replace that command with `az acr credential show -n guideRegistry --query "passwords[0].value" -o tsv`? This command is used widely by other azure guides. This command automatically only gets the 1st password, and doesn't confuse the user why there's another password.

Use command `az acr credential show -n guideRegistry --query "passwords[0].value" -o tsv`

**Comment by gkwan-ibm** [comment]
>   Running one of the following command holds the command prompt, so perhaps they should be separated into 2 command boxes?
> 
> 
> ```
> kubectl get service/system-service -w
> kubectl get service/inventory-service -w
> ```

Update that section to have a logical flow.

**Comment by evelinec** [comment]
> > * [ ]  The --admin-enabled flag indicates that the admin user is enabled.
> >   => this flag is not used in the command `az acr create -g guideGroup -n guideRegistry --sku Basic --admin-enabled`.
> >   => Ah, I realized later that the problem is that this command is long and it's not displayed entirely when the browser screen is not maximized. So this is an UI issue that need to be addressed, imo.
> 
> > * [ ]  Some longer commands like this one below is not showing up entirely on the command box, and can't be scrolled to display it as well. This seems like a UI issue, and it's not good, imo. Note, I didn't capture all of the impacted command, as I wasn't sure whether it was cut off or not.
> >   ![image](https://user-images.githubusercontent.com/33134427/60290215-42ac5100-98e6-11e9-84db-4e7138cda504.png)`
> 
> This is a UI issue, that occurs on the openliberty.io site and draft site:
> [OpenLiberty/openliberty.io#1235](https://github.com/OpenLiberty/openliberty.io/issues/1235)

Good to see the issue on openliberty.io. But there's no owner for it. I think we'd request to get it fix soon.

**Comment by evelinec** [comment]
> > @evelinec
> > > "It also returns the pod’s name in the HTTP header, making replicas easy to distinguish from each other. The inventory microservice adds the properties from the system microservice to the inventory. This demonstrates how communication can be established between pods inside a cluster."
> > > => For the mentioned of "pods" in this section, there's no explanation of what it is. I think for a fresh user, it may be helpful.
> > 
> > 
> > Question:
> > The paragraph above is the same as the one in the "What you'll learn" section in the cloud-aws guide and cloud-ibm guide, and in those guides there is no previous explanation of what "pods" are. Should I keep it consistent with those guides? Or should I add a section explaining what pods are, and then make an issue for the other 2 cloud guides to add a pod section in there too?
> 
> We can keep it consistent with aws and ibm cloud guides. Because there is a link to the "Deploying microservices to Kubernetes" guide where explains what "pod" is. No need to explain in the cloud guides

The link to the kube-intro guide is not in the same paragraph as the pods are being mentioned, but it's above this paragraph. Hopefully user does go through that. I'm fine with this.

**Comment by evelinec** [comment]
> > For the Docker prereq, it's good to add another sentence for user to start the docker daemon, if they already have docker installed previously. This is needed at one of the step (ie, `az acr login -n guideRegistry`) later, but it wasn't mentioned to have it running.
> 
> It is not necessary to add the statement "Your Docker daemon must be started in order to perform the steps of this guide." The reasons are:
> 
> * keep the consistent as other Cloud guides and guides using Docker
> * "daemon" maybe a term for unix platform and not for Windows
> 
> So, remove that statement

Perhaps to say start the docker? ie, at the end of the same bullet, add, "If you already have Docker installed, make sure you have it running"? @gkwan-ibm what do you think? 

I don't think we need to state it in a sub-bullet.

**Comment by evelinec** [comment]
> > Took a while to install Azure CLI on my MacOS system, as there were a few permission issues, ie, failed to create folder under /usr/local directory, failed to make symbolic links within this folder, etc. Had to manually create a folder and change some folder's permissions with the sudo command to get through with the installation.
> 
> I tried the command to install Azure CLI (from the link on the guide: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest), which was `brew update && brew install azure-cli`, on a different Mac and it worked fine. So i think it might be a problem with your Mac system specifically.

Ok. Thank you for trying it out again. I'm not sure what can be done with this neither. It's fine.

**Comment by evelinec** [comment]
Couple things I found not being addressed: 
- If `kubectl` is installed on the system an user is working already, does it need to be up to date?
- Pushing the images to a registry allows the cluster to create pods by using your container images. 
=> Optionally may be good to add a short reminder description of what pods are, may be helpful to some users. Or perhaps why to create pods?
- I think at this point, the kubenetes services, ie, from the Docker Desktop on Mac, should be started, but it wasn't instructed to do so. Perhaps adding a sentence to have it started at the prereqs would be enough and useful.

New issues: 
- [ ] The new docker tag commends for the system and inventory services shows up in one line: `docker tag system:latest guideregistry.azurecr.io/system docker tag inventory:latest guideregistry.azurecr.io/inventory`

- [ ] Same with the docker push commands: `docker push guideregistry.azurecr.io/system docker push guideregistry.azurecr.io/inventory`

**Comment by evelinec** [comment]
Other feedback are all good. Thank you.

**Comment by gkwan-ibm** [comment]
>     * If `kubectl` is installed on the system an user is working already, does it need to be up to date?

As I know, we do not have this requirement to use the latest version. Also, unless we exactly know which version not work, then we can ask readers to use certain or above version.

**Comment by NimG98** [comment]
> New issues: 
> - [ ] The new docker tag commends for the system and inventory services shows up in one line: `docker tag system:latest guideregistry.azurecr.io/system docker tag inventory:latest guideregistry.azurecr.io/inventory`
> - [ ] Same with the docker push commands: `docker push guideregistry.azurecr.io/system docker push guideregistry.azurecr.io/inventory`

This is a new UI issue that appeared after the fix for the previous command box issue: https://github.com/OpenLiberty/openliberty.io/issues/1233. I messaged Steven about this issue and he said this issue will be addressed soon.

**Comment by gkwan-ibm** [comment]
>    Pushing the images to a registry allows the cluster to create pods by using your container images.
>       => Optionally may be good to add a short reminder description of what pods are, may be helpful to some users. Or perhaps why to create pods?

Assuming readers understand what is a pod and at "What you’ll learn" section, readers can check out  the "Deploying microservices to Kubernetes" guide where describes "pod" at the subsection "What is Kubernetes?" .

**Comment by gkwan-ibm** [comment]
>   I think at this point, the kubenetes services, ie, from the Docker Desktop on Mac, should be started, but it wasn't instructed to do so. Perhaps adding a sentence to have it started at the prereqs would be enough and useful.

The kubernetes service is no need to be started for the cloud guides. Only need the `kubectl` command.

**Comment by evelinec** [comment]
> > I think at this point, the kubenetes services, ie, from the Docker Desktop on Mac, should be started, but it wasn't instructed to do so. Perhaps adding a sentence to have it started at the prereqs would be enough and useful.
> 
> The kubernetes service is no need to be started for the cloud guides. Only need the `kubectl` command.

Just verified this point again as well. You're right, it doesn't need to be started. Thanks.

**Comment by evelinec** [comment]
> > Pushing the images to a registry allows the cluster to create pods by using your container images.
> > => Optionally may be good to add a short reminder description of what pods are, may be helpful to some users. Or perhaps why to create pods?
> 
> Assuming readers understand what is a pod and at "What you’ll learn" section. And, readers can check out the "Deploying microservices to Kubernetes" guide where describes "pod" at the subsection "What is Kubernetes?" .

For consistency reason, it's ok as it is currently stated. No change needed. Thanks.

**Comment by evelinec** [comment]
> > If `kubectl` is installed on the system an user is working already, does it need to be up to date?
> 
> As I know, we do not have this requirement to use the latest version. Also, unless we exactly know which version not work, then we can ask readers to use certain or above version.

Ok.

**Comment by evelinec** [comment]
Looking good. Closed.
