### ISSUE TITLE
Code feedback

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-cloud-azure#5]
- [x] The `SystemData.java` file doesn't have a license header?

- [x] `Cloud` is current not a visible tag for the UI. Specifying it in the `:page-tags:` field is not appearing on the website.

**Comment by NimG98** [comment]
> - [ ] `Cloud` is current not a visible tag for the UI. Specifying it in the `:page-tags:` field is not appearing on the website. 

---
The cloud-aws guide and cloud-ibm guide also don't have `Cloud` as visible UI tags. 

I checked the [draft-guide-template github wiki](https://github.com/OpenLiberty/draft-guides-template/wiki/README-breakdown) for making the README, and they mention that the tags need to be one out of the specified list to be displayed:

![image](https://user-images.githubusercontent.com/46586499/60391498-9de46c00-9abd-11e9-8e77-1acfe0e909b5.png)


![image](https://user-images.githubusercontent.com/46586499/60391538-92457500-9abe-11e9-941b-3008de705976.png)


I think this might be a UI issue, where they need to add `Cloud` as a tag that should be allowed to be visible. Should I open an issue for this?

**Comment by NimG98** [comment]
> - [ ] The `SystemData.java` file doesn't have a license header?

---
All of the cloud guides and kubernetes guides don't have a license header for `SystemData.java` in the finish or start directories. I can open an issue to add the license for all guides?

**Comment by NimG98** [comment]
Issue for fixing licensing for all `SystemData.java` files: https://github.com/OpenLiberty/guides-common/issues/301

**Comment by NimG98** [comment]
Issue for making `Cloud` appear on the UI under "Tags" section: https://github.com/OpenLiberty/openliberty.io/issues/1247

**Comment by NimG98** [comment]
PR for adding `Cloud` tag to visible-tags.liquid: https://github.com/OpenLiberty/openliberty.io/pull/1248

**Comment by NimG98** [comment]
PR merged into master, `Cloud` tag now visibly shows up on site.
