### ISSUE TITLE
Test script feedback

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-cloud-azure#7]
- [x] Don't need the `printf` statements in the TravisTest script. The `set -euxo pipefail` flag prints every command that executes in this script. 

- [x] Don't think it's good idea to keep a `kubernetes.yaml` file in the script directory just for testing, unless it's very specific to test? Otherwise, it's good to use the one under the finish directory. In case changes are made in the future for this yaml file and those changes needed to be made in multiple places. It may very easily be forgotten for the one under the script directory. In fact, your test is running in the `finish` directory, you really don't need another copy of the yaml file. As well, the 2 copies are identical.

**Comment by NimG98** [comment]
Renamed `kubernetes.yaml` in the `scripts` folder to `test.yaml`, and removed print statements from travis script

**Comment by evelinec** [comment]
Changes looks good! Thank you. Closed.
