### ISSUE TITLE
SME review feedback

### ISSUE THREAD

**Issue by jkwong888** [OpenLiberty/draft-guide-cloud-azure#8]
- [x] in this sentence:

> A cloud-based infrastructure enables you to focus on developing your microservices without worrying about details related to the servers you deploy them to. Using a cloud helps you to easily scale and serve your microservices in a high-availability setup.

perhaps it bears mentioning that the cloud vendor is managing the infrastructure, and it's actually just the control plane that is managed while the user is still responsible for securing the networks and the perimeter around the networks that the worker nodes are provisioned to. the use of "you" here in this guide assumes the audience is developers that are writing the code, but there's likely going to be build, deploy, SRE folks that may be reading this guide and stuff "you" might not need to worry about is actually of high importance to those people.  Perhaps changing "you" in this sentence to "developers" ;)

- [ ] the order of the steps in creating the infrastructure might be confusing as we are provisioning the container registry, then building the code, then building the cluster.  I think a natural order of things is that a developer has code that he/she has built on their local machine and wants to deploy it to a cloud environment.  I like the following order better:

  - compile the code
  - build the docker images and run them locally (this might be in a different guide already)
  - create container registry
  - push image to container registry
  - create AKS cluster
  - deploy the app

- [ ] the container registry is created with `--admin-enabled` which I don't think we should recommend as the credentials become string-based username/passwords that can easily be lost or stolen.  Microsoft recommends assigning `acrPull` role to the AKS service principal.  Can we change the steps to:

   1. Create the registry:

      ```
      az acr create -g guideGroup -n guideRegistry --sku Basic
      ```

   1. Create the cluster (no change)
   1. login to the registry (no change) -- but a statement here about the token expiry in case the user takes a break between guide steps 
   1. Remove the step regarding getting the ACR credentials
   1. assign the `acrPull` role to the aks cluster's service principal:

      get the registry's resource ID:
      ```
      az acr show --resource-group guideGroup --name guideRegistry --query "id" --output tsv
      ```

      get the cluster's service principal app ID:
      ```
      az aks show -g guideGroup -n guideCluster --query servicePrincipalProfile.clientId -o tsv
      ```

      assign the role to the cluster:
      ```
      az role assignment create --assignee <cluster app Id> --scope <registry resource ID> --role acrpull
      ```
   1. remove the step regarding creating the registry secrets

- [x] When building the microservices, we should explain how different teams may be organized around microservices and remove the monolithic build step that builds both services with one command (the top level `mvn package`) as this isn't realistic or we shouldn't be promoting this.  it should be fine to have to build each microservice individually.

- [x] do we want to have the user run/verify the microservices locally?

- [x] when tagging the images, we leave off the image tags on the remote registry, which implies `latest`.  we should explicitly put some version number (perhaps v0.0.1) developers will not be able to track versions if they are just pushing to `latest` all the time.

   ```
   docker tag system:latest guideregistry.azurecr.io/system:v0.0.1
   docker tag inventory:latest guideregistry.azurecr.io/inventory:v0.0.1
   ```

- [x] During cluster creation, we specify `--generate-ssh-keys` which will add the local ssh public key (or generate one) to the worker nodes of the cluster.  However we stated in the introduction that developers shouldn't need to worry about infrastructure management, and SSH'ing into worker nodes is kind of management.  Perhaps we should remove that argument.  There is documentation on adding SSH keys to the cluster after the fact, and a developer's only interaction with the AKS cluster should probably just be through the kubernetes control plane.

- [x] In this statement:

> An AKS cluster requires a service principal, which is a security credential that allows you to assign specific permissions for Azure resources accessed by applications and services. 

the service principal is not a "security credential" but rather an identity used to represent a resource in Azure and can be assigned roles and permissions to interact with other resources and the Azure API.  For example, the service principal created by default in AKS will be given permissions to create load balancers and block devices in response to objects that are created inside of Kubernetes.  I am not sure if you tested with an existing service principal but if they were created with a custom role, the load balancers will not be created in the following steps.

 - [ ] each microservice is exposed on individual ports which is good for local development, but when running on kubernetes we can actually have the `Service` resource listen on port 80 and forward to the container port.  for example:

   ```
   apiVersion: v1
   kind: Service
   metadata:
     name: system-service
   spec:
     type: LoadBalancer
     selector:
       app: system
     ports:
     - protocol: TCP
        port: 80
        targetPort: 9080
   ```

   The selection of `port` affects what port the service/load balancer listens on, while `targetPort` will tell kubernetes which port on the container to forward the traffic to. Users running through the guide may be behind firewalls and these do not always allow outgoing connections on port 9080, but 80 seems to be more common.

- [ ] Do both the `system` and `inventory` services both need to be exposed through a load balancer?  One possibility could be to change the guide slightly so that `system` is not exposed at all and `inventory` is used to query the various systems.  `system` microservices might represent backend systems or services that we don't want to expose to the internet but we provide `inventory` service as a sort of reverse proxy/API we can use to query about systems in the backend.

   we can leave `inventory` as is, but remove the `system` service, and scale it up to more instances, then use:

   ```
   kubectl get pods -o jsonpath='{range .items[*]}{.status.podIP}{"\n"}{end}' -l app=system
   ```

   to retrieve the pod IP addresses, e.g.:
   ```
   10.244.0.10
   10.244.1.6
   10.244.1.7
   10.244.2.7
   10.244.2.9
   ```

   then we can use the loadbalancer to load the systems information.  It might bear mentioning how pod networking works in Kubernetes where each pod gets its own ephemeral IP address, and when they crash or are redeployed the IPs change dynamically.

   If we want to run a test against system locally without exposing a load balancer, we can forward the ports through the control plane:

   ```
   kubectl port-forward deployment/system-deployment 15000:9080
   ```

   This forwards localhost port 15000 to port 9080 on one of the containers, then we can use the browser at `localhost:15000` to get at our system container.

   This might change some of the inventory verification tests though

**Comment by NimG98** [comment]
> - [ ] when tagging the images, we leave off the image tags on the remote registry, which implies `latest`.  we should explicitly put some version number (perhaps v0.0.1) developers will not be able to track versions if they are just pushing to `latest` all the time.
> ```
> docker tag system:latest guideregistry.azurecr.io/system:v0.0.1
> docker tag inventory:latest guideregistry.azurecr.io/inventory:v0.0.1
> ```

We are using `1.0-SNAPSHOT` now instead of `latest`, so now the commands will look like:

```
docker tag system:1.0-SNAPSHOT guideregistry.azurecr.io/system:1.0-SNAPSHOT
docker tag inventory:1.0-SNAPSHOT guideregistry.azurecr.io/inventory:1.0-SNAPSHOT
```
---

> During cluster creation, we specify `--generate-ssh-keys` which will add the local ssh public key (or generate one) to the worker nodes of the cluster. However we stated in the introduction that developers shouldn't need to worry about infrastructure management, and SSH'ing into worker nodes is kind of management. Perhaps we should remove that argument. There is documentation on adding SSH keys to the cluster after the fact, and a developer's only interaction with the AKS cluster should probably just be through the kubernetes control plane.

Okay I will remove it then!

**Comment by NimG98** [comment]
The following points would not be consistent with the structure of OpenLiberty guides:

---

> - [ ] in this sentence:
> A cloud-based infrastructure enables you to focus on developing your microservices without worrying about details related to the servers you deploy them to. Using a cloud helps you to easily scale and serve your microservices in a high-availability setup.

>> perhaps it bears mentioning that the cloud vendor is managing the infrastructure, and it's actually just the control plane that is managed while the user is still responsible for securing the networks and the perimeter around the networks that the worker nodes are provisioned to. the use of "you" here in this guide assumes the audience is developers that are writing the code, but there's likely going to be build, deploy, SRE folks that may be reading this guide and stuff "you" might not need to worry about is actually of high importance to those people.  Perhaps changing "you" in this sentence to "developers" ;)

The format of our guides always involve writing "you", so just for consistency we will leave "you".

---

> Do both the system and inventory services both need to be exposed through a load balancer? One possibility could be to change the guide slightly so that system is not exposed at all and inventory is used to query the various systems. 

We are currently looking into changing the infrastructure of `system` and `inventory` in all of our guides. But until there is a final decision, we are trying to keep this guide consistent with other guides. So, for now, we will keep both system and inventory exposed. 

---

> When building the microservices, we should explain how different teams may be organized around microservices and remove the monolithic build step that builds both services with one command (the top level `mvn package`) as this isn't realistic or we shouldn't be promoting this. it should be fine to have to build each microservice individually.

Majority of our guides, including the ones building microservices, use `mvn install` or `mvn package`.

---

> - [ ] the order of the steps in creating the infrastructure might be confusing as we are provisioning the container registry, then building the code, then building the cluster.  I think a natural order of things is that a developer has code that he/she has built on their local machine and wants to deploy it to a cloud environment.  I like the following order better:
>  - compile the code
>  - build the docker images and run them locally (this might be in a different guide already)
>  - create container registry
>  - push image to container registry
>  - create AKS cluster
>  - deploy the app





I like this structure too :)

We will implement this but with a slight change, since the guide is being changed to use `dockerfile-maven-plugin`. So `mvn package` will automatically start the `dockerfile-maven:build` goal, picks up the Dockerfile that is located in the same directory as its POM file and builds a Docker image from it.


The order that we have currently was to keep all of the docker related commands grouped together in one section. Instead of building the docker images in the beginning and not touching them until much later in the guide.
