### ISSUE TITLE
Running process with port 9080 after tear down

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-cloud-azure#9]
Happened to find that after performing the tear down steps of this guide, there's still a running process that holds the 9080 port.. This is not good.

**Comment by yeekangc** [comment]
Was the local process a local running process?  What process was that?  Do we have data?  Please share if you do, @evelinec.

The deployment should be remote so this is weird and should be looked at.  FYI, @gkwan-ibm.

**Comment by evelinec** [comment]
Yes, it was local running process, for the liberty server (somehow). I had talked to @NimG98 about it, and she was able to reproduce it. I believe she's working on it.

**Comment by yeekangc** [comment]
Thanks, @evelinec.  @NimG98. please share findings and root cause ASAP.

**Comment by NimG98** [comment]
I could reproduce the problem and there was a java process running after going through the guide.

I did `ps -ef | grep java` after each command in the guide to see when the java process pops up. And it pops up after i run the `mvn verify` command near the end of the guide.

I've used some similar code to the draft-guide-microservices-docker guide, which also has a process still running by the end of the guide (issue: https://github.com/OpenLiberty/draft-guide-microservices-docker/issues/14).  

I'm still looking into the cause of this problem, but I will try to compare to the other cloud guides (which don't leave a running process in the end) to see if I am missing something.

**Comment by NimG98** [comment]
I also noticed that the URL (http://localhost:9080/system/properties) is accessible after tearing down

**Comment by NimG98** [comment]
The following change now causes there to be no running Java process at the end of the guide:

In the inventory/pom.xml, the `<activeByDefault>` tag (under `teardown-test` profile) needed to be changed from false to true, in order to stop the system service from running after the tests.

![image](https://user-images.githubusercontent.com/46586499/61405293-6f310880-a8a7-11e9-9b98-9dd8b2ee000f.png)
